// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Tk0xaFQDuZosZ61e4-m5EswfnopSKe0',
    appId: '1:268777861370:web:725484f5335253f6f91943',
    messagingSenderId: '268777861370',
    projectId: 'full-6fce8',
    authDomain: 'full-6fce8.firebaseapp.com',
    storageBucket: 'full-6fce8.firebasestorage.app',
    measurementId: 'G-GSTR58WD1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEOQ6Wr6v4xzMn5fDyU9oyPEC7pX2F3Z0',
    appId: '1:268777861370:android:5492cac0f57762ebf91943',
    messagingSenderId: '268777861370',
    projectId: 'full-6fce8',
    storageBucket: 'full-6fce8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS0NCeRa7YXcMUCKLx-_jWeja8O-FIDT8',
    appId: '1:268777861370:ios:e91752ccb805faa3f91943',
    messagingSenderId: '268777861370',
    projectId: 'full-6fce8',
    storageBucket: 'full-6fce8.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS0NCeRa7YXcMUCKLx-_jWeja8O-FIDT8',
    appId: '1:268777861370:ios:e91752ccb805faa3f91943',
    messagingSenderId: '268777861370',
    projectId: 'full-6fce8',
    storageBucket: 'full-6fce8.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7Tk0xaFQDuZosZ61e4-m5EswfnopSKe0',
    appId: '1:268777861370:web:3fad49614c49ed3bf91943',
    messagingSenderId: '268777861370',
    projectId: 'full-6fce8',
    authDomain: 'full-6fce8.firebaseapp.com',
    storageBucket: 'full-6fce8.firebasestorage.app',
    measurementId: 'G-KTPJNT2YQ9',
  );
}
